<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AzuAnticheat</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="AzuAnticheat.translations.German.yml" />
    <None Remove="AzuAnticheat.translations.Russian.yml" />
    <None Remove="AzuAnticheat.translations.English.yml" />
    <None Remove="ILRepack.List" />
    <None Remove="Expression.Visitor" />
    <EmbeddedResource Include="AzuAnticheat.translations.German.yml" LogicalName="AzuAnticheat.translations.German.yml" />
    <EmbeddedResource Include="AzuAnticheat.translations.Russian.yml" LogicalName="AzuAnticheat.translations.Russian.yml" />
    <EmbeddedResource Include="AzuAnticheat.translations.English.yml" LogicalName="AzuAnticheat.translations.English.yml" />
    <EmbeddedResource Include="ILRepack.List" LogicalName="ILRepack.List" />
    <EmbeddedResource Include="Expression.Visitor" LogicalName="Expression.Visitor" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>..\..\..\..\..\AppData\Roaming\com.kesomannen.gale\valheim\profiles\newtest\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="assembly_valheim">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\assembly_valheim.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\..\..\AppData\Roaming\com.kesomannen.gale\valheim\profiles\newtest\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="assembly_guiutils">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\assembly_guiutils.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\..\..\..\..\AppData\Roaming\com.kesomannen.gale\valheim\profiles\newtest\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\assembly_utils.dll</HintPath>
    </Reference>
    <Reference Include="Splatform">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\Splatform.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="gui_framework">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\gui_framework.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
